services:
  backend:
    build:
      context: ./src
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgresql://sistema_vendas_dugp_user:GmVnOSCBXs6n85ivGVXezERzuE2rfdp4@dpg-d1ujm415pdvs73fnf2og-a.oregon-postgres.render.com:5432/sistema_vendas_dugp
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
      
  tests:
    build:
      context: ./src
    volumes:   
      - ./src:/app
    environment:
      - PYTHONPATH=/app
    command: ["pytest", "--disable-warnings", "-v"]
    depends_on:
      - backend

  lint:
    build: 
      context: ./src
    volumes:
      - ./src:/app
    environment:
      - PYTHONPATH=/app
    command: ["pylint", "--disable=R,C", "."]
